### ISSUE TITLE
Add functions to download decennial population at block level

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#3]
+ Download decennial population data at the block level
    + Use `c.sf1`
    + Example: `c.sf1.get('P001001', geo={'for': 'block:*',
                                           'in': 'state:36 county:085'})`
+ Aggregate to a given geography. Current use-cases are floodplain, and park-access zone, and community district aggregation
    + Unlike ACS data, there is no MOE

**Comment by SPTKL** [comment]
the `census` package actually has decennial endpoints built in
https://github.com/datamade/census

**Comment by SPTKL** [comment]
we might have to change the language in the calculation object 
```json
{
        "pff_variable": "fpop35t39",
        "acs_variable": [
            "B01001_037"
        ],
        "decennial_variable":[
            "xxxxxxxxxx"
        ],
        "domain" : "demographics",
        "base_variable": "pop",
        "rounding": 0,
        "source": ""
}
```
or 
```json
{
        "pff_variable" : "fpop35t39",
        "census_variable" : [
            "B01001_037"
        ],
        "census_type" : "acs/decennial",
        "domain" : "demographics",  
        "base_variable": "pop",
        "rounding": 0,
        "source": ""
}
```

**Comment by mgraber** [comment]
@SPTKL I was thinking something like this:
```json
{
        "pff_variable": "pop2010",
        "census_variable": [
            "P001001"
        ],
        "domain": "",
        "base_variable": "",
        "rounding": 0,
        "median": false,
        "source": "decennial",
        "range": [],
        "design_factor": 0
    }
```
Where existing instances of `acs_variable` get changed to `census_variable` and we distinguish based on `source`

**Comment by SPTKL** [comment]
source is used for identifying "profile"/"subject" for acs variables, we can probably change it to some other name tho.
Also from a usability perspective, we should do 1 meta data object
```json
{
   'acs' : [.....],
   'decennial': [.....]
} 
```
in the class attributes, we can do
`pff.acs_metadata`
`pff.decennial_metadata`

it's annoying because there are variables with the same name in acs and decennial, so we would need to do something like 
`pff.calculate_variable('mdage', 'NTA', 2018, 'acs)`

I wish we can do something like 
`pff.acs.calculate_variable('mdage', 'NTA', 2018)`
`pff.decennial.calculate_variable('mdage', 'NTA', 2010)`

but it gets into class inheritance stuff, I haven't learned how to do it yet

**Comment by SPTKL** [comment]
we should also change all the `acs_geoid` to `census_geoid`
